= CTRAN

An attempt to reverse-engineer `CTRAN.EXE`, the Psion Object Oriented C preprocessor.
In Pascal.

== Aims

* A drop-in replacement for the original `CTRAN.EXE` in the Psion SIBO C SDK, replicating both the input switches and the generated files.
* Run on modern OSes and DOS.
* Produce identical files to the original (3.43 or 5.02 -- see below).
* Allow multiple include sources.

== Targets for v1.00

* [x] Psion Category file lexer
* [x] Psion Category file parser/AST builder
* [ ] Command line parser
* [ ] Build class dependency tree
* [ ] Generate `.ext` files
* [ ] Generate `.c` files
* [ ] Generate `.g` files
* [ ] Generate `.asm` files
* [ ] Generate `.ing` files
* [ ] Generate `.lis` files

== What is (or was) `CTRAN`?

`CTRAN.EXE` is a pre-processor for the object-oriented part of Psion's SIBO C SDK, targeting the SIBO/EPOC16 range of portable devices.
It takes a `.cat` category file containing class definitions (methods, properties, etc) and generates the following files:

* A `.c` file
* A `.g` header file, to be `#include`d with the class's methods.
* A `.ext` file with a summary of the class that can be reused by `CTRAN`
* A `.asm` file
* A `.ing` file (assembly header)
* A `.lis` file

Normally only the first three are used.
It can also generate alternative versions of files for inclusion within the SDK, plus skeleton source files from which to build methods.

== The problem

My main gripe with the original `CTRAN.EXE` is that it can only include files from one folder.
So, if you want to include the `ROOT` class in OLIB (the main OO library) and one of your own classes, they both have to be in the same location.
This means that you have to store every generated file inside the SDK folder.

I did not like this.

== Different versions of `CTRAN.EXE`

There are two main versions of Psion's `CTRAN`:

* 3.43: This came with the SIBO C SDK 2.20 and is (probably) the version that most people using the SDK would have.
* 5.02: This came with Psion OVAL 1.21, an IDE based on Visual Basic 6 that could be used to create new controls for use in EPOC16 applications, as well as entire EPOC16 applications.
This version of `CTRAN` generates cleaner code than the previous version, and fixes some (but not all) bugs in 3.43.
It adds the ability to generate files for OVAL controls.
It also adds a (very broken) feature for generating code for EPOC32.

The original aim was to reach feature-parity with 3.43.
However, if 5.02 doesn't introduce any breaking changes, then the new `CTRAN` will aim to mimic the code that it generates.
OVAL-related features won't be in v1.00, but might be added in a later release.
The EPOC32 "feature" will not be added to the new `CTRAN`.

== Why (Object) Pascal?

I want this to run on all modern operating systems, as well as DOS.
I didn't want to write it in C or C++, so I went hunting for another language/compiler.

Free Pascal offers just the right level of language, taking away some of the worries of memory management and how to handle dictionaries/trees, while letting me go low-level when I want to.
It targets pretty much everything, including Linux, Windows, macOS, Haiku, *BSD... and both 16-bit and 32-bit DOS.

Unfortunately, some of Free Pascal's units are too big to fit into 64KB code chunks, so the new CTRAN will target 32-bit DOS using a DPMI extender.
This won't affect how `CTRAN` works.
As most people will be running `CTRAN` in DOSBox, it shouldn't affect anyone.

== The future

At some point the entire SDK needs to be moved away from DOSBox.
This will require rewriting every single tool that was included in the SDK, plus the TopSpeed C compiler.

There is a lot of work to do, but rewriting `CTRAN` as a FOSS project is the first step.

